feat(spec-filter): allow custom specFilter
karma-runner/karma-jasmine pull request #290
Opened 2021-07-03 21:19 UTC by nicojs

Allow users to define their own jasmine `specFilter`.

```js
jasmine.getEnv().configure({
  specFilter: function(spec) {
    // ...
  }
})
```

2021-07-03 21:23 UTC, nicojs commented
@johnjbarton It has been [more than a year](https://github.com/karma-runner/karma-jasmine/issues/256#issuecomment-618454830), but here it is 😅

2021-11-21 09:38 UTC, nicojs commented
@johnjbarton do you think you can find time to take a look at this? It's an important feature for StrykerJS users

2022-04-12 21:30 UTC, nicojs commented
@jginsburgn would you please be so kind to review this PR? It is actually breaking StrykerJS for karma-jasmine users (they experience false negatives on timeouts)

2022-04-13 00:05 UTC, jginsburgn commented
> @jginsburgn would you please be so kind to review this PR? It is actually breaking StrykerJS for karma-jasmine users (they experience false negatives on timeouts)

Surely. Please resolve the conflicts!

2022-04-13 06:19 UTC, nicojs commented
@jginsburgn thanks in advance! Just resolved the conflicts

2022-04-24 10:24 UTC, devoto13 submitted a review, later dismissed
LGTM

Sorry that it took so long to review!

2022-04-25 03:07 UTC, jginsburgn requested changes
@nicojs can you add some documentation in the README file?

2022-05-29 09:22 UTC, nicojs commented
@jginsburgn sorry I didn't catch that 2 months ago. Added a remark in the readme 📖

2022-06-16 02:41 UTC, jginsburgn approved these changes

2022-06-16 02:41 UTC, merged

2022-06-16 20:45 UTC, nicojs commented
Thanks @jginsburgn 😍